version: "{build}"
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: >-
    dotnet tool install dotnet-housework -g

    dotnet housework setbuildnumber %CiVersion% build.ini

    dotnet housework author ./src/Parquet/Parquet.csproj  build.ini

    dotnet housework author ./src/SharpArrow/SharpArrow.csproj build.ini

    dotnet housework author ./src/Parquet.CLI/Parquet.CLI.csproj build.ini

    dotnet housework substitute ./src/Parquet/ThriftFooter.cs build.ini -r

    dotnet restore src/Parquet.sln
build:
  project: src/Parquet.sln
  verbosity: minimal
test_script:
- cmd: >-
   dotnet test src\Parquet.Test -c release
artifacts:
- path: src/**/*.nupkg
deploy: off